apiVersion: v1
kind: Secret
metadata:
  name: anime-backlog-secrets
  namespace: anime-backlog
type: Opaque
stringData:
  POSTGRES_PASSWORD: change-me
  AUTH_OWNER_USERNAME: change-me
  AUTH_OWNER_PASSWORD: change-me
  AUTH_SESSION_SECRET: change-me